### ISSUE TITLE
Get value in controller?

### ISSUE THREAD

**Issue by umairrazzaq** [amstel91/otp-input-directive#1]
Any way to get value in controller? I've treid `$scope.otpInput` & `$scope.otpInput.value` but not be able to get output value, also no luck with `controller.otpInput` & `controller.otpInput.value`.

Also any clue how we bind this with `ng-model`?

Your help on this would be highly appreciable?

**Comment by amstel91** [comment]
If you see the below plunker there is output printed which is in the controller scope.
{{otpInput.value}}
This is set in the options you send.
http://plnkr.co/edit/eCHuJT?p=preview

Please paste the code in the comments if you still have issues.

**Comment by umairrazzaq** [comment]
I'm getting following error. I've tried different approaches, but still no luck. Please check my code below.

**Error**
`ReferenceError: otpInput is not defined`

**View**
```
<div ng-controller="RegisterEmailVerifyController">
    <div class="otp-verification-control" ng-model="RegisterEmailController.userDetail.email_otp" otp-input-directive options="otpInput"></div>
    <button ng-click="RegisterEmailVerifyController.nexStep()" class="btn btn-primary">Next Step</button>
</div>
```

**Controller**
```
RegisterEmailVerifyController.$inject = ['$scope', '$state', '$http', 'userFactory'];
function RegisterEmailVerifyController($scope, $state, $http, userFactory) {
    var controller = this;

    $scope.ErrorMsg = '';
    $scope.otpInput = {
        size : 4,
        type : 'text'
        // onDone: function(value) { console.log(value) },
        // onChange: function(value) { console.log(value) }
    }

    controller.userDetail = {};

    controller.nexStep = function () {
        if ( controller.userDetail.useremail ) {
            $http({
                method: "POST",
                url: "http://apirequest.io:8080/webservices/signUp/email-otp",
                headers: {
                    "Content-Type": "application/json"
                },
                params: {
                    "email": controller.userDetail.useremail
                }
            }).then(function mySuccess(response) {
                console.log(response);
                console.log(otpInput.value);    <---
                $state.go('register.user')
            }, function myError(response) {
                console.log(otpInput.value);    <---
                console.log(response);
            });
        } else {
            console.log("There is some issue with form validation");
            return;
        }
        userFactory.setData(controller.userDetail);
    }	
}
```

Based on above markup and setting, i need to make sure that user has to put some value on fields and than can submit, there i need to do some validation first than i also need to send otp value in api request, but i can't be able to retrieve value so far.

**Let me list requirements here.**
- Validation check if user fill these fields (I'm able to do so on other input fields with ng-modal, but not on this one)
- Possible way to bind this with ng-modal so i can get its value in data array that I've set for registration form.
- Retrieving value from controller as console.

Thanks for reading my query.

**Comment by umairrazzaq** [comment]
Anything to add on it?

**Comment by amstel91** [comment]
As of now ng-model is not supported. To access the value in controller use $scope.otpInput.value. 
If it is not working can you create a plunker for your issue?
