### ISSUE TITLE
Checking if number is correct

### ISSUE THREAD

**Issue by MaartenV87** [amstel91/otp-input-directive#3]
Hi Amstel91,

I'm a teacher looking for a digit combination passcode script to create an online escape room for my students. In my search I stumbled on your Github.
My knowledge of programming is not that good.
I woulld like to now if it's hard to include a function where the scripts checks the input for a code and if correct gets redirected to a webpage?

Thank you for your contribution!

**Comment by amstel91** [comment]
Hi MaartenV87,
               This Directive works with AngularJS. If you have an AngularJS application you can use this directive and onDone/onChange you can validate the code and redirect to a webpage. Hope this makes sense.
